[package]
name = "grand-warden-rofl"
version = "1.0.0"
edition = "2021"

[dependencies]
# Minimal dependencies for ROFL testing
tokio = { version = "1.35", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"