[package]
name = "grand-warden-rofl"
version = "1.0.0"
edition = "2021"

[features]
default = []
sui = []

[dependencies]
# Core async runtime
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread", "signal"] }

# HTTP client with retry support  
reqwest = { version = "0.11", features = ["json", "gzip"] }

# Blockchain integration - ethers with abigen support
ethers = { version = "2.0", features = ["legacy", "rustls", "abigen"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Persistence with exactly-once semantics
sled = "0.34"
bincode = "1.3"

# Metrics - using metrics_exporter_prometheus
metrics = "0.22"
metrics-exporter-prometheus = "0.13"

# HTTP server for metrics
axum = { version = "0.7", features = ["tokio"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

# Retry logic with exponential backoff
tokio-retry = "0.3"

# Jitter for retry delays
rand = "0.8"

# Additional utilities
uuid = { version = "1.0", features = ["v4"] }
hex = "0.4"
url = "2.4"

# No build dependencies needed - using inline abigen

[dev-dependencies]
tempfile = "3.8"