services:
  mycontainer:
    # remove build: for ROFL; image must be pullable from a registry
    image: docker.io/shaddymy/grand-warden-rofl:latest
    platform: linux/amd64
    environment:
      # keep only the vars you really use (or define as ROFL secrets)
      - TOKEN=${TOKEN}
    volumes:
      # persistent storage inside TEE (optional)
      - /storage/rofl-storage:/app/rofl-storage
      # ROFL control socket (if your app needs it)
      - /run/rofl-appd.sock:/run/rofl-appd.sock