services:
  mycontainer:
    # Build locally using the Dockerfile
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      # keep only the vars you really use (or define as ROFL secrets)
      - TOKEN=${TOKEN}
      - PHALA_API_KEY=${PHALA_API_KEY}
      - REDPILL_API_BASE=${REDPILL_API_BASE}
      - REDPILL_API_PATH=${REDPILL_API_PATH}
      - REDPILL_MODEL=${REDPILL_MODEL}
    volumes:
      # persistent storage inside TEE (optional)
      - ./rofl-storage:/app/rofl-storage